#Question: True/False - If a cup contains hot coffee, then the cup is presumably right side up.

CONSTRUCT {?s mcs:hasOrientation mcs:rightSideUp} 
WHERE {?s mcs:contains ?y}

ASK WHERE {mcs:cup mcs:hasOrientation mcs:rightSideUp}


#Minimum knowledge:
#   a cup must be right side up if it contains something
#   "is" can be interpreted as "has orientation"
