#Question: True/False - Grandfather clocks are bigger than pocket watches.

CONSTRUCT {?s mcs:isLargerThan ?y} 
WHERE {mcs:pocket mcs:contains ?y .
    ?s mcs:hasProperty mcs:tall .}

ASK WHERE {mcs:grandfatherClock mcs:isLargerThan mcs:pocketWatch}


#Minimum knowledge:
#   pocket contains a pocket watch
#   grandfather clock is tall (alternative approach: sits on floor?)
#   if an object is tall, it likely cannot fit in a pocket
#   "bigger" and "larger" are synonyms
