#Question: True/False - You are likely to find a bathtub in a kitchen.

CONSTRUCT {?s MCS::isFoundIn ?y} 
WHERE {?s MCS::contains ?y}

ASK WHERE {MCS::bathtub MCS::isFoundIn MCS::kitchen}


#Minimum knowledge:
#   a kitchen does not contain a bathtub
