#Question: True/False - You are likely to find a bathtub in a kitchen.

CONSTRUCT {?s mcs:isFoundIn ?y} 
WHERE {?s mcs:contains ?y}

ASK WHERE {mcs:bathtub mcs:isFoundIn mcs:kitchen}


#Minimum knowledge:
#   a kitchen does not contain a bathtub
