#Question: True/False - A parking garage is larger than an automobile.

CONSTRUCT {?s mcs:isLargerThan ?y} 
WHERE {?s mcs:contains ?y}

ASK WHERE {mcs:parkingGarage mcs:isLargerThan mcs:automobile}


#Minimum knowledge:
#   parkingGarage contains vehicles
#   automobile is-a vehicle
#   container is larger than the thing it contains
