#Question: True/False - You can ship a book in a box that is smaller than the book is.

CONSTRUCT {?y MCS::isSmallerThan ?s} 
WHERE {?s MCS::contains ?y}

CONSTRUCT {?s MCS::fitsInside ?y} 
WHERE {?y MCS::isSmallerThan ?s}

ASK WHERE {MCS::book MCS::fitsInside MCS::box .
    MCS::box MCS::isSmallerThan MCS::book .}


#Minimum knowledge:
#   an object must be smaller than another to fit inside of it
