#Question: True/False - If Joy is on the first floor, and Rob is on the second floor, then Joy is above Rob.

CONSTRUCT {?y mcs:isLocatedAbove ?s} 
WHERE {?s mcs:locatedAt mcs:firstFloor .
    ?y mcs:locatedAt mcs:secondFloor .}

ASK WHERE {mcs:joy mcs:isLocatedAbove mcs:rob}


#Minimum knowledge:
#   the first floor is below the second floor
