#Question: True/False - If Joy is on the first floor, and Rob is on the second floor, then Joy is above Rob.

CONSTRUCT {?y MCS::isLocatedAbove ?s} 
WHERE {?s MCS::locatedAt MCS::firstFloor .
    ?y MCS::locatedAt MCS::secondFloor .}

ASK WHERE {MCS::joy MCS::isLocatedAbove MCS::rob}


#Minimum knowledge:
#   the first floor is below the second floor
